### ISSUE TITLE
it seems that the bot is broken because your password should be set to hang him from the trees

### ISSUE THREAD

**Issue by Technoguyfication** [sysadam/Ultimate-Michael-Jackson-Discord-Bot#3]
I couldn't help but notice right here:
![](http://tkno.pw/2aGl236)

...you indicated your bot doesn't work

perhaps you should try and set your password correctly in the code to resolve this issue

**Comment by sysadam** [comment]
how about you stop bullying poor little me

**Comment by GusCaplan** [comment]
i think this should be reopened, as the issue wasn't really addressed

**Comment by sysadam** [comment]
i changed the password, so the issue does not apply anymore

**Comment by Hammster** [comment]
I guess, lesson learned :+1:

**Comment by sysadam** [comment]
it was a test bot, so it wouldn't have mattered anyway
